FROM gradle:8.5-jdk21 AS build
WORKDIR /home/gradle/src
COPY . .
RUN gradle :web-app:bootJar --no-daemon

FROM eclipse-temurin:21-jdk-jammy
WORKDIR /app
COPY --from=build /home/gradle/src/web-app/build/libs/*.jar ./app.jar
RUN apt-get update && \
    apt-get install -y python3

EXPOSE 8079
ENTRYPOINT [ "java", "-jar", "app.jar" ]